P017 IRIS数据-加载认识数据

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
iris["filename"]

'iris.csv'

In [5]:
iris["data"][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
iris["target"][:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

P018 IRIS数据-查看列名和分类名

In [7]:
iris["feature_names"]


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
import pandas as pd

In [9]:
pd.DataFrame(data=iris["data"], columns=iris["feature_names"])

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

P019 IRIS数据-数据和目标的shape

In [11]:
data = iris["data"]

In [12]:
type(data)

numpy.ndarray

In [13]:
data.shape

(150, 4)

In [14]:
target = iris["target"]

In [15]:
type(target)

numpy.ndarray

In [16]:
data.shape

(150, 4)

In [17]:
pd.Series(target).unique()

array([0, 1, 2])

P020 IRIS数据-拆分训练测试集

In [18]:
data.shape

(150, 4)

In [19]:
target.shape

(150,)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
data_train, data_test, target_train, target_test = \
    train_test_split(data, target, test_size=0.3)

In [22]:
data_train.shape

(105, 4)

In [23]:
target_train.shape

(105,)

In [24]:
data_test.shape

(45, 4)

In [25]:
target_test.shape

(45,)

P021 IRIS数据-逻辑回归训练 Logistic regression training

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression(max_iter=1000)

In [28]:
model.fit(data_train, target_train)

LogisticRegression(max_iter=1000)

In [29]:
model.score(data_train, target_train)

0.9809523809523809

In [30]:
model.score(data_test, target_test)

0.9777777777777777

P022 IRIS数据-在测试集上实现预估

In [31]:
model

LogisticRegression(max_iter=1000)

In [32]:
data_test.shape

(45, 4)

In [33]:
target_pred = model.predict(data_test)

In [34]:
target_pred.shape

(45,)

In [35]:
target_test.shape

(45,)

P023 IRIS数据-理解混淆矩阵

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 21,  1],
       [ 0,  0,  9]], dtype=int64)

P024 IRIS数据-理解分类报告

In [38]:
from sklearn.metrics import classification_report

In [39]:
print(classification_report(target_test, target_pred,
                           target_names=iris["target_names"]))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       1.00      0.95      0.98        22
   virginica       0.90      1.00      0.95         9

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45

